package model;
// Generated 27/04/2016 13:04:06 by Hibernate Tools 3.6.0

import java.sql.SQLException;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import persistence.CursoDAO;

/**
 * Curso generated by hbm2java
 */
@Entity
@Table(name = "curso", catalog = "scc"
)
public class Curso implements java.io.Serializable {
    
    private int codigo;
    private String nome;
    private String descricao;
    private String cargaHoraria;
    private String palestrante;
    private String data;
    private String hora;
    private String laboratorio;
    private Integer vagas;
    
    public Curso() {
    }
    
    public Curso(int codigo) {
        this.codigo = codigo;
    }
    
    public Curso(int codigo, String nome, String descricao, String cargaHoraria, String palestrante, String data, String hora, String laboratorio, Integer vagas) {
        this.codigo = codigo;
        this.nome = nome;
        this.descricao = descricao;
        this.cargaHoraria = cargaHoraria;
        this.palestrante = palestrante;
        this.data = data;
        this.hora = hora;
        this.laboratorio = laboratorio;
        this.vagas = vagas;
    }
    
    @Id
    
    @Column(name = "codigo", unique = true, nullable = false)
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    
    @Column(name = "nome", length = 45)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    
    @Column(name = "descricao", length = 150)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    
    @Column(name = "carga_horaria", length = 45)
    public String getCargaHoraria() {
        return this.cargaHoraria;
    }
    
    public void setCargaHoraria(String cargaHoraria) {
        this.cargaHoraria = cargaHoraria;
    }
    
    @Column(name = "palestrante", length = 45)
    public String getPalestrante() {
        return this.palestrante;
    }
    
    public void setPalestrante(String palestrante) {
        this.palestrante = palestrante;
    }
    
    @Column(name = "data", length = 45)
    public String getData() {
        return this.data;
    }
    
    public void setData(String data) {
        this.data = data;
    }
    
    @Column(name = "hora", length = 45)
    public String getHora() {
        return this.hora;
    }
    
    public void setHora(String hora) {
        this.hora = hora;
    }

    @Column(name = "laboratorio", length = 10)
    public String getLaboratorio() {
        return laboratorio;
    }
    
    public void setLaboratorio(String laboratorio) {
        this.laboratorio = laboratorio;
    }
    
    @Column(name = "vagas")
    public Integer getVagas() {
        return this.vagas;
    }
    
    public void setVagas(Integer vagas) {
        this.vagas = vagas;
    }
    
    public static List<Curso> obterCursos() throws ClassNotFoundException, SQLException {
        return CursoDAO.getInstance().obterCursos();
    }
    
}
