package model;
// Generated 27/04/2016 13:04:06 by Hibernate Tools 3.6.0

import java.sql.SQLException;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import persistence.TipousuarioDAO;

/**
 * Tipousuario generated by hbm2java
 */
@Entity
@Table(name = "tipousuario", catalog = "scc"
)
public class Tipousuario implements java.io.Serializable {

    private int id;
    private String tipo;

    public Tipousuario() {
    }

    public Tipousuario(int id) {
        this.id = id;
    }

    public Tipousuario(int id, String tipo) {
        this.id = id;
        this.tipo = tipo;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "tipo", length = 45)
    public String getTipo() {
        return this.tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    public static Tipousuario obterTipo(int id) throws ClassNotFoundException,
            SQLException {
        return TipousuarioDAO.obterTipo(id);
    }

    public static List<Tipousuario> obterTipos() throws ClassNotFoundException,
            SQLException {
        return TipousuarioDAO.obterTipos();
    }

}
