package model;
// Generated 27/04/2016 13:04:06 by Hibernate Tools 3.6.0

import java.sql.SQLException;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import persistence.UsuarioDAO;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", catalog = "scc"
)
public class Usuario implements java.io.Serializable {

    private int matricula;
    private Tipousuario tipousuario;
    private String nome;
    private String email;
    private String senha;

    public Usuario() {
    }

    public Usuario(int matricula) {
        this.matricula = matricula;
    }

    public Usuario(int matricula, String nome, String email, String senha, Tipousuario tipousuario) {
        this.matricula = matricula;
        this.tipousuario = tipousuario;
        this.nome = nome;
        this.email = email;
        this.senha = senha;
    }

    @Id

    @Column(name = "matricula", unique = true, nullable = false)
    public int getMatricula() {
        return this.matricula;
    }

    public void setMatricula(int matricula) {
        this.matricula = matricula;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TipoUsuario_id")
    public Tipousuario getTipousuario() {
        return this.tipousuario;
    }

    public void setTipousuario(Tipousuario tipousuario) {
        this.tipousuario = tipousuario;
    }

    @Column(name = "nome", length = 45)
    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    @Column(name = "email", length = 45)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "senha", length = 45)
    public String getSenha() {
        return this.senha;
    }

    public void setSenha(String senha) {
        this.senha = senha;
    }

    public static Usuario obterUsuario(String email, String senha) throws ClassNotFoundException,
            SQLException {
        return UsuarioDAO.getInstance().obterUsuario(email, senha);
    }

    public static Usuario obterUsuario(int matricula) throws ClassNotFoundException, SQLException {
        return UsuarioDAO.getInstance().obterUsuario(matricula);
    }

    public static List<Usuario> obterUsuarios() throws ClassNotFoundException,
            SQLException {
        return UsuarioDAO.getInstance().obterUsuarios();
    }

}
